name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKE_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/simple-app:${{github.run_id }}

    # Checkout the simple-app-devops repository
    - name: Checkout simple-app-devops Repo
      uses: actions/checkout@v3
      with:
        repository: biraluu/simple-app-devops
        token: ${{ secrets.PAT_TOKEN }}
        path: simple-app-devops

    # Update Kubernetes Manifest with New Image
    - name: Update Kubernetes Manifest
      run: |
        IMAGE_TAG=${{ github.run_id }}
        yq -i '.spec.template.spec.containers[0].image = "biraluu/simple-app:" + strenv(IMAGE_TAG)' simple-app-devops/simple-app-deployment.yml

    # Commit Updated Manifest to simple-app-devops
    - name: Commit Changes to simple-app-devops
      run: |
        cd simple-app-devops
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add simple-app-deployment.yml
        git commit -m "Update image to biraluu/simple-app:${{ github.run_id }}"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
